''
CREATE EXTERNAL TABLE "claims"."stage_apcd_claim_ccw"
  ([id_apcd] BIGINT NULL, 
  [from_date] DATE NULL, 
  [to_date] DATE NULL, 
  [ccw_code] TINYINT NULL, 
  [ccw_desc] VARCHAR(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_claim_ccw');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_claim_header"
  ([id_apcd] BIGINT NULL, 
  [claim_header_id] BIGINT NULL, 
  [product_code_id] INT NULL, 
  [first_service_date] DATE NULL, 
  [last_service_date] DATE NULL, 
  [first_paid_date] DATE NULL, 
  [last_paid_date] DATE NULL, 
  [charge_amt] NUMERIC(38,2) NULL, 
  [primary_diagnosis] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [icdcm_version] TINYINT NULL, 
  [claim_status_id] INT NULL, 
  [claim_type_apcd_id] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [claim_type_id] TINYINT NULL, 
  [type_of_bill_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [cardiac_imaging_and_tests_flag] TINYINT NULL, 
  [chiropractic_flag] TINYINT NULL, 
  [consultations_flag] TINYINT NULL, 
  [covid19_flag] TINYINT NULL, 
  [dialysis_flag] TINYINT NULL, 
  [durable_medical_equip_flag] TINYINT NULL, 
  [echography_flag] TINYINT NULL, 
  [endoscopic_procedure_flag] TINYINT NULL, 
  [evaluation_and_management_flag] TINYINT NULL, 
  [health_home_utilization_flag] TINYINT NULL, 
  [hospice_utilization_flag] TINYINT NULL, 
  [imaging_advanced_flag] TINYINT NULL, 
  [imaging_standard_flag] TINYINT NULL, 
  [inpatient_acute_flag] TINYINT NULL, 
  [inpatient_nonacute_flag] TINYINT NULL, 
  [lab_and_pathology_flag] TINYINT NULL, 
  [oncology_and_chemotherapy_flag] TINYINT NULL, 
  [physical_therapy_rehab_flag] TINYINT NULL, 
  [preventive_screenings_flag] TINYINT NULL, 
  [preventive_vaccinations_flag] TINYINT NULL, 
  [preventive_visits_flag] TINYINT NULL, 
  [psychiatric_visits_flag] TINYINT NULL, 
  [surgery_and_anesthesia_flag] TINYINT NULL, 
  [telehealth_flag] TINYINT NULL, 
  [ed_perform_id] BIGINT NULL, 
  [ed_pophealth_id] BIGINT NULL, 
  [inpatient_id] BIGINT NULL, 
  [discharge_date] DATE NULL, 
  [pc_visit_id] BIGINT NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_claim_header');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_claim_icdcm_header"
  ([id_apcd] BIGINT NULL, 
  [claim_header_id] BIGINT NULL, 
  [first_service_date] DATE NULL, 
  [last_service_date] DATE NULL, 
  [icdcm_raw] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [icdcm_norm] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [icdcm_version] TINYINT NULL, 
  [icdcm_number] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_claim_icdcm_header');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_claim_line"
  ([id_apcd] BIGINT NULL, 
  [claim_header_id] BIGINT NULL, 
  [claim_line_id] BIGINT NULL, 
  [line_counter] INT NULL, 
  [first_service_date] DATE NULL, 
  [last_service_date] DATE NULL, 
  [charge_amt] NUMERIC(38,2) NULL, 
  [revenue_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [place_of_service_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [admission_date] DATE NULL, 
  [discharge_date] DATE NULL, 
  [discharge_status_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [admission_point_of_origin_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [admission_type] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_claim_line');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_claim_preg_episode"
  ([id_apcd] BIGINT NULL, 
  [age_at_outcome] NUMERIC(18,0) NULL, 
  [age_at_outcome_cat6] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [preg_episode_id] BIGINT NULL, 
  [preg_endpoint] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [preg_hier] TINYINT NULL, 
  [preg_start_date] DATE NULL, 
  [preg_end_date] DATE NULL, 
  [ga_days] INT NULL, 
  [ga_weeks] NUMERIC(4,1) NULL, 
  [valid_start_date] TINYINT NULL, 
  [valid_ga] TINYINT NULL, 
  [valid_both] TINYINT NULL, 
  [lb_type] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [ga_estimation_step] TINYINT NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_claim_preg_episode');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_claim_procedure"
  ([id_apcd] BIGINT NULL, 
  [claim_header_id] BIGINT NULL, 
  [first_service_date] DATE NULL, 
  [last_service_date] DATE NULL, 
  [procedure_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [procedure_code_number] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [modifier_1] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [modifier_2] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [modifier_3] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [modifier_4] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_claim_procedure');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_claim_provider"
  ([id_apcd] BIGINT NULL, 
  [claim_header_id] BIGINT NULL, 
  [first_service_date] DATE NULL, 
  [last_service_date] DATE NULL, 
  [provider_id_apcd] BIGINT NULL, 
  [provider_id_raw_apcd] BIGINT NULL, 
  [provider_type] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_claim_provider');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_demo"
  ([id_apcd] BIGINT NULL, 
  [dob] DATE NULL, 
  [ninety_only] TINYINT NULL, 
  [gender_me] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_demo');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_timevar"
  ([id_apcd] BIGINT NULL, 
  [from_date] DATE NULL, 
  [to_date] DATE NULL, 
  [contiguous] TINYINT NULL, 
  [med_covgrp] TINYINT NULL, 
  [pharm_covgrp] TINYINT NULL, 
  [dental_covgrp] TINYINT NULL, 
  [med_medicaid] TINYINT NULL, 
  [med_medicare] TINYINT NULL, 
  [med_commercial] TINYINT NULL, 
  [med_unknown] TINYINT NULL, 
  [pharm_medicaid] TINYINT NULL, 
  [pharm_medicare] TINYINT NULL, 
  [pharm_commercial] TINYINT NULL, 
  [pharm_unknown] TINYINT NULL, 
  [dental_medicaid] TINYINT NULL, 
  [dental_medicare] TINYINT NULL, 
  [dental_commercial] TINYINT NULL, 
  [dental_unknown] TINYINT NULL, 
  [dual] TINYINT NULL, 
  [geo_zip] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_wa] TINYINT NULL, 
  [geo_kc] TINYINT NULL, 
  [cov_time_day] BIGINT NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_timevar');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2014"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2014');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2015"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2015');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2016"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2016');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2017"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2017');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2018"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2018');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2019"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2019');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2020"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2020');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2021"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2021');

''
CREATE EXTERNAL TABLE "claims"."stage_apcd_elig_plr_2022"
  ([id_apcd] BIGINT NULL, 
  [geo_wa] TINYINT NULL, 
  [overall_mcaid] TINYINT NULL, 
  [overall_mcaid_med] TINYINT NULL, 
  [overall_mcaid_pharm] TINYINT NULL, 
  [medical_coverage_6mo] TINYINT NULL, 
  [medical_coverage_7mo] TINYINT NULL, 
  [medical_coverage_11mo] TINYINT NULL, 
  [geo_zip] VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_county] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [geo_ach_covd] BIGINT NULL, 
  [geo_ach_covper] NUMERIC(4,1) NULL, 
  [age] NUMERIC(25,0) NULL, 
  [age_grp7] VARCHAR(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_me] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_recent] VARCHAR(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [gender_female] TINYINT NULL, 
  [gender_male] TINYINT NULL, 
  [race_eth_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_me] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_eth_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_recent] VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [race_aian] TINYINT NULL, 
  [race_asian] TINYINT NULL, 
  [race_black] TINYINT NULL, 
  [race_latino] TINYINT NULL, 
  [race_nhpi] TINYINT NULL, 
  [race_white] TINYINT NULL, 
  [race_unknown] TINYINT NULL, 
  [med_total_covd] BIGINT NULL, 
  [med_total_covper] NUMERIC(4,1) NULL, 
  [dual_covd] BIGINT NULL, 
  [dual_covper] NUMERIC(4,1) NULL, 
  [dual] TINYINT NULL, 
  [med_medicaid_covd] BIGINT NULL, 
  [med_medicare_covd] BIGINT NULL, 
  [med_commercial_covd] BIGINT NULL, 
  [med_medicaid_covper] NUMERIC(4,1) NULL, 
  [med_medicare_covper] NUMERIC(4,1) NULL, 
  [med_commercial_covper] NUMERIC(4,1) NULL, 
  [pharm_total_covd] BIGINT NULL, 
  [pharm_total_covper] NUMERIC(4,1) NULL, 
  [pharm_medicaid_covd] BIGINT NULL, 
  [pharm_medicare_covd] BIGINT NULL, 
  [pharm_commercial_covd] BIGINT NULL, 
  [pharm_medicaid_covper] NUMERIC(4,1) NULL, 
  [pharm_medicare_covper] NUMERIC(4,1) NULL, 
  [pharm_commercial_covper] NUMERIC(4,1) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'stage_apcd_elig_plr_2022');
