
USE [PHClaims];
GO

TRUNCATE TABLE [ref].[mcaid_prvdr_txnmy];

INSERT INTO [ref].[mcaid_prvdr_txnmy]
([taxonomy_code]
,[desc]
,[cms_taxonomy_group]
,[cms_specialty_code])

SELECT 
 CAST([PROVIDER.TAXONOMY.CODE] AS VARCHAR(200)) AS [taxonomy_code]
,CAST([PROVIDER.TAXONOMY.DESCRIPTION] AS VARCHAR(1000)) AS [desc]
,CAST([MEDICARE.PROVIDER/SUPPLIER.TYPE.DESCRIPTION] AS VARCHAR(200)) AS [cms_taxonomy_group]
,CAST([MEDICARE.SPECIALTY.CODE] AS VARCHAR(200)) AS [cms_specialty_code]
FROM [tmp].[CROSSWALK_MEDICARE_PROVIDER_SUPPLIER_to_HEALTHCARE_PROVIDER_TAXONOMY_CLEANED.xlsx]
WHERE [DUPLICATE] IS NULL;
GO

SELECT * 
FROM [ref].[mcaid_prvdr_txnmy];

IF OBJECT_ID('[tmp].[CROSSWALK_MEDICARE_PROVIDER_SUPPLIER_to_HEALTHCARE_PROVIDER_TAXONOMY_CLEANED.xlsx]') IS NOT NULL
DROP TABLE [tmp].[CROSSWALK_MEDICARE_PROVIDER_SUPPLIER_to_HEALTHCARE_PROVIDER_TAXONOMY_CLEANED.xlsx];