--Code to create stage.apcd_eligibility
--Eli Kern (PHSKC-APDE)
--2019-6-27

if object_id('PHClaims.stage.apcd_eligibility', 'U') is not null
	drop table PHClaims.stage.apcd_eligibility;
create table PHClaims.stage.apcd_eligibility (
	[eligibility_id] [bigint] NULL,
	[extract_id] [int] NULL,
	[submitter_id] [int] NULL,
	[internal_member_id] [bigint] NULL,
	[coverage_class] [varchar](10) NULL,
	[eligibility_start_dt] [date] NULL,
	[eligibility_end_dt] [date] NULL,
	[product_code_id] [int] NULL,
	[product_code] [varchar](20) NULL,
	[primary_insurance_indicator_id] [int] NULL,
	[primary_insurance_ind_code] [varchar](20) NULL,
	[subscriber_relationship_id] [int] NULL,
	[subscriber_relationship_code] [varchar](10) NULL,
	[gender_code] [varchar](2) NULL,
	[age] [int] NULL,
	[age_in_months] [int] NULL,
	[coverage_level_id] [int] NULL,
	[coverage_level_code] [varchar](20) NULL,
	[coverage_type_id] [int] NULL,
	[coverage_type_code] [varchar](20) NULL,
	[market_category_id] [int] NULL,
	[market_category_code] [varchar](4) NULL,
	[entitlement_code_id] [int] NULL,
	[entitlement_code] [varchar](20) NULL,
	[entitlement_code_id_orig] [int] NULL,
	[entitlement_code_orig] [varchar](20) NULL,
	[medicare_advantage_id] [int] NULL,
	[medicare_advantage_code] [varchar](20) NULL,
	[medicare_status_id] [int] NULL,
	[medicare_status_code] [varchar](20) NULL,
	[dual_eligibility_code_id] [int] NULL,
	[dual_eligibility_code] [varchar](10) NULL,
	[aid_category_id] [int] NULL,
	[aid_category_code] [varchar](20) NULL,
	[managed_care_flag] [varchar](1) NULL,
	[purchased_through_exchange] [varchar](100) NULL,
	[exchange_market_type] [varchar](2) NULL,
	[exchange_metallic_tier_id] [int] NULL,
	[exchange_metallic_tier_code] [varchar](20) NULL,
	[city] [varchar](100) NULL,
	[state] [varchar](2) NULL,
	[zip] [varchar](5) NULL,
	[medicaid_ffs_flag] [varchar](2) NULL,
	[race_id1] [int] NULL,
	[race_code1] [varchar](20) NULL,
	[race_id2] [int] NULL,
	[race_code2] [varchar](20) NULL,
	[ethnicity_id1] [int] NULL,
	[ethnicity_code1] [varchar](20) NULL,
	[ethnicity_id2] [int] NULL,
	[ethnicity_code2] [varchar](20) NULL,
	[hispanic_id] [int] NULL,
	[hispanic_code] [varchar](20) NULL,
	[behavioral_health_ind_code] [varchar](10) NULL,
	[age_65_flag] [varchar](1) NULL,
	[out_of_state_flag] [varchar](1) NULL,
	[dup_flag_pbm_tpa] [varchar](1) NULL,
	[dup_flag_managed_care] [varchar](1) NULL,
	[dup_flag_part_d] [varchar](1) NULL	
)
on [PRIMARY];



