--Code to create stage.apcd_inpatient_stay_summary_ltd
--Eli Kern (PHSKC-APDE)
--2019-6-27

if object_id('PHClaims.stage.apcd_inpatient_stay_summary_ltd', 'U') is not null
	drop table PHClaims.stage.apcd_inpatient_stay_summary_ltd;
create table PHClaims.stage.apcd_inpatient_stay_summary_ltd (
	[inpatient_discharge_id] [bigint] NULL,
	[extract_id] [bigint] NULL,
	[internal_member_id] [bigint] NULL,
	[place_of_setting_id] [bigint] NULL,
	[first_service_dt] [date] NULL,
	[last_service_dt] [date] NULL,
	[admit_dt] [date] NULL,
	[discharge_dt] [date] NULL,
	[discharge_status_id] [bigint] NULL,
	[discharge_status_code] [varchar](20) NULL,
	[length_of_stay] [int] NULL,
	[gender_code] [varchar](2) NULL,
	[age] [int] NULL,
	[admit_diagnosis_code] [varchar](20) NULL,
	[primary_diagnosis_code] [varchar](20) NULL,
	[diagnosis_code_1] [varchar](20) NULL,
	[diagnosis_code_2] [varchar](20) NULL,
	[diagnosis_code_3] [varchar](20) NULL,
	[diagnosis_code_4] [varchar](20) NULL,
	[diagnosis_code_5] [varchar](20) NULL,
	[diagnosis_code_6] [varchar](20) NULL,
	[diagnosis_code_7] [varchar](20) NULL,
	[diagnosis_code_8] [varchar](20) NULL,
	[diagnosis_code_9] [varchar](20) NULL,
	[diagnosis_code_10] [varchar](20) NULL,
	[diagnosis_code_11] [varchar](20) NULL,
	[diagnosis_code_12] [varchar](20) NULL,
	[diagnosis_code_13] [varchar](20) NULL,
	[diagnosis_code_14] [varchar](20) NULL,
	[diagnosis_code_15] [varchar](20) NULL,
	[diagnosis_code_16] [varchar](20) NULL,
	[diagnosis_code_17] [varchar](20) NULL,
	[diagnosis_code_18] [varchar](20) NULL,
	[diagnosis_code_19] [varchar](20) NULL,
	[diagnosis_code_20] [varchar](20) NULL,
	[diagnosis_code_21] [varchar](20) NULL,
	[diagnosis_code_22] [varchar](20) NULL,
	[diagnosis_code_23] [varchar](20) NULL,
	[diagnosis_code_24] [varchar](20) NULL,
	[diagnosis_code_25] [varchar](20) NULL,
	[diagnosis_code_26] [varchar](20) NULL,
	[diagnosis_code_27] [varchar](20) NULL,
	[diagnosis_code_28] [varchar](20) NULL,
	[diagnosis_code_29] [varchar](20) NULL,
	[diagnosis_code_30] [varchar](20) NULL,
	[icd_procedure_code_1] [varchar](10) NULL,
	[icd_procedure_code_2] [varchar](10) NULL,
	[icd_procedure_code_3] [varchar](10) NULL,
	[icd_procedure_code_4] [varchar](10) NULL,
	[icd_procedure_code_5] [varchar](10) NULL,
	[icd_procedure_code_6] [varchar](10) NULL,
	[icd_procedure_code_7] [varchar](10) NULL,
	[icd_procedure_code_8] [varchar](10) NULL,
	[icd_procedure_code_9] [varchar](10) NULL,
	[icd_procedure_code_10] [varchar](10) NULL,
	[icd_procedure_code_11] [varchar](10) NULL,
	[icd_procedure_code_12] [varchar](10) NULL,
	[icd_procedure_code_13] [varchar](10) NULL,
	[icd_procedure_code_14] [varchar](10) NULL,
	[icd_procedure_code_15] [varchar](10) NULL,
	[icd_procedure_code_16] [varchar](10) NULL,
	[icd_procedure_code_17] [varchar](10) NULL,
	[icd_procedure_code_18] [varchar](10) NULL,
	[icd_procedure_code_19] [varchar](10) NULL,
	[icd_procedure_code_20] [varchar](10) NULL,
	[icd_procedure_code_21] [varchar](10) NULL,
	[icd_procedure_code_22] [varchar](10) NULL,
	[icd_procedure_code_23] [varchar](10) NULL,
	[icd_procedure_code_24] [varchar](10) NULL,
	[icd_procedure_code_25] [varchar](10) NULL,
	[icd_procedure_code_26] [varchar](10) NULL,
	[icd_procedure_code_27] [varchar](10) NULL,
	[icd_procedure_code_28] [varchar](10) NULL,
	[icd_procedure_code_29] [varchar](10) NULL,
	[icd_procedure_code_30] [varchar](10) NULL,
	[icd_version_ind] [varchar](2) NULL
)
on [PRIMARY];



