--Code to load data to stage.apcd_inpatient_stay_summary_ltd
--Eli Kern (PHSKC-APDE)
--2019-6-27

------------------
--STEP 1: Insert data into table shell
-------------------
insert into PHClaims.stage.apcd_inpatient_stay_summary_ltd with (tablock)
select
[inpatient_discharge_id]
,[extract_id]
,[internal_member_id]
,[place_of_setting_id]
,[first_service_dt]
,[last_service_dt]
,[admit_dt]
,[discharge_dt]
,[discharge_status_id]
,[discharge_status_code]
,[length_of_stay]
,[gender_code]
,[age]
,[admit_diagnosis_code]
,[primary_diagnosis_code]
,[diagnosis_code_1]
,[diagnosis_code_2]
,[diagnosis_code_3]
,[diagnosis_code_4]
,[diagnosis_code_5]
,[diagnosis_code_6]
,[diagnosis_code_7]
,[diagnosis_code_8]
,[diagnosis_code_9]
,[diagnosis_code_10]
,[diagnosis_code_11]
,[diagnosis_code_12]
,[diagnosis_code_13]
,[diagnosis_code_14]
,[diagnosis_code_15]
,[diagnosis_code_16]
,[diagnosis_code_17]
,[diagnosis_code_18]
,[diagnosis_code_19]
,[diagnosis_code_20]
,[diagnosis_code_21]
,[diagnosis_code_22]
,[diagnosis_code_23]
,[diagnosis_code_24]
,[diagnosis_code_25]
,[diagnosis_code_26]
,[diagnosis_code_27]
,[diagnosis_code_28]
,[diagnosis_code_29]
,[diagnosis_code_30]
,[icd_procedure_code_1]
,[icd_procedure_code_2]
,[icd_procedure_code_3]
,[icd_procedure_code_4]
,[icd_procedure_code_5]
,[icd_procedure_code_6]
,[icd_procedure_code_7]
,[icd_procedure_code_8]
,[icd_procedure_code_9]
,[icd_procedure_code_10]
,[icd_procedure_code_11]
,[icd_procedure_code_12]
,[icd_procedure_code_13]
,[icd_procedure_code_14]
,[icd_procedure_code_15]
,[icd_procedure_code_16]
,[icd_procedure_code_17]
,[icd_procedure_code_18]
,[icd_procedure_code_19]
,[icd_procedure_code_20]
,[icd_procedure_code_21]
,[icd_procedure_code_22]
,[icd_procedure_code_23]
,[icd_procedure_code_24]
,[icd_procedure_code_25]
,[icd_procedure_code_26]
,[icd_procedure_code_27]
,[icd_procedure_code_28]
,[icd_procedure_code_29]
,[icd_procedure_code_30]
,[icd_version_ind]
from PHclaims.load_raw.apcd_inpatient_stay_summary_ltd;



