--1. Select the last entry for each person (MEDICAID_RECIPIENT_ID) PER YEAR for the eligibility table
-- Lin Song 2016-06-15

SELECT *,
ROW_NUMBER() OVER(PARTITION BY MEDICAID_RECIPIENT_ID, CAL_YEAR ORDER BY CAL_YEAR, MEDICAID_RECIPIENT_ID, FROM_DATE DESC) AS ROW
FROM PHClaims.dbo.vEligibility

WITH UNDUP AS (
SELECT *,
ROW_NUMBER() OVER(PARTITION BY MEDICAID_RECIPIENT_ID, CAL_YEAR ORDER BY CAL_YEAR, MEDICAID_RECIPIENT_ID, FROM_DATE DESC) AS ROW
FROM PHClaims.dbo.vEligibility
)
SELECT * 
FROM UNDUP 
WHERE ROW=1;

SELECT DISTINCT MEDICAID_RECIPIENT_ID
FROM PHClaims.dbo.vEligibility
WHERE CAL_YEAR<2016;


--2. select unique addresses for geocoding
DROP TABLE #A
SELECT DISTINCT ADRS_LINE_1, ADRS_LINE_2, CITY_NAME AS CITY, POSTAL_CODE AS ZIPCODE INTO #A
FROM PHClaims.dbo.vEligibility
WHERE CAL_YEAR<2016;

ALTER TABLE #A ADD ADDRESS CHARACTER(80);
UPDATE #A SET ADDRESS=ADRS_LINE_1;
UPDATE #A SET ADDRESS=ADRS_LINE_2 WHERE ADRS_LINE_2 LIKE '[1-9]%';

SELECT * FROM #A
WHERE ADRS_LINE_2<>'NULL'
ORDER BY ADRS_LINE_2;


DROP TABLE #B
SELECT ADDRESS, CITY, ZIPCODE,
SUBSTRING(ADDRESS, 0, CHARINDEX('APT', ADDRESS) ) AS APT1,
SUBSTRING(ADDRESS, 0, CHARINDEX('#', ADDRESS) ) AS APT2,
SUBSTRING(ADDRESS, 0, CHARINDEX('UNIT', ADDRESS) ) AS APT3,
SUBSTRING(ADDRESS, 0, CHARINDEX('TRLR', ADDRESS) ) AS APT4,
SUBSTRING(ADDRESS, 0, CHARINDEX('STE', ADDRESS) ) AS APT5
INTO #B
FROM #A;

UPDATE #B SET ADDRESS=APT1 WHERE APT1<>'';
UPDATE #B SET ADDRESS=APT2 WHERE APT2<>'';
UPDATE #B SET ADDRESS=APT3 WHERE APT3<>'';
UPDATE #B SET ADDRESS=APT4 WHERE APT4<>'';
UPDATE #B SET ADDRESS=APT5 WHERE APT5<>'';

ALTER TABLE #B
DROP COLUMN APT1, APT2, APT3;

DROP TABLE #C
SELECT DISTINCT ADDRESS, CITY, ZIPCODE INTO #C
FROM #B
WHERE ADDRESS LIKE '[1-9]%' AND ADDRESS<>'1';

SELECT * FROM #C
ORDER BY ADDRESS;
