''
CREATE EXTERNAL TABLE "claims"."stage_mcare_claim_header"
  ([id_mcare] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL, 
  [claim_header_id] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL, 
  [first_service_date] DATE NULL, 
  [last_service_date] DATE NULL, 
  [primary_diagnosis] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [icdcm_version] TINYINT NULL, 
  [claim_type_mcare_id] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [claim_type_id] TINYINT NULL, 
  [filetype_mcare] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [facility_type_code] TINYINT NULL, 
  [service_type_code] TINYINT NULL, 
  [patient_status] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [patient_status_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [ccs_superlevel_desc] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [ccs_broad_desc] VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [ccs_broad_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [ccs_midlevel_desc] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [ccs_detail_desc] VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [ccs_detail_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [mh_primary] TINYINT NULL, 
  [mh_any] TINYINT NULL, 
  [sud_primary] TINYINT NULL, 
  [sud_any] TINYINT NULL, 
  [injury_nature_narrow] TINYINT NULL, 
  [injury_nature_broad] TINYINT NULL, 
  [injury_nature_type] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [injury_nature_icdcm] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [injury_ecode] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [injury_intent] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [injury_mechanism] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,     
  [ed_perform] TINYINT NULL, 
  [ed_perform_id] BIGINT NULL, 
  [ed_pophealth] TINYINT NULL, 
  [ed_pophealth_id] BIGINT NULL, 
  [inpatient] TINYINT NULL, 
  [inpatient_id] BIGINT NULL, 
  [admission_date] DATE NULL, 
  [discharge_date] DATE NULL, 
  [ipt_admission_type] TINYINT NULL, 
  [ipt_admission_source] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [drg_code] VARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
  [hospice_from_date] DATE NULL, 
  [pc_visit] TINYINT NULL, 
  [pc_visit_id] BIGINT NULL, 
  [submitted_charges] NUMERIC(38,2) NULL, 
  [total_paid_mcare] NUMERIC(38,2) NULL, 
  [total_paid_insurance] NUMERIC(38,2) NULL, 
  [total_paid_bene] NUMERIC(38,2) NULL, 
  [total_cost_of_care] NUMERIC(38,2) NULL, 
  [last_run] DATETIME NULL)
WITH (DATA_SOURCE = [datascr_WS_EDW], SCHEMA_NAME = N'stg_claims', OBJECT_NAME = N'final_mcare_claim_header');
