###############################################################################
# Eli Kern
# 2018-1-16

# Code to create a SQL table dbo.mcaid_elig_gender which holds Medicaid member gender by ID and time period
# Use to select a gender-based cohort for a given data range
# Data elements: ID, gender, from date, to date 

###############################################################################


##### Set up global parameter and call in libraries #####
options(max.print = 350, tibble.print_max = 30, scipen = 999)

library(RODBC) # Used to connect to SQL server
library(openxlsx) # Used to import/export Excel files
library(car) # used to recode variables
library(stringr) # Used to manipulate string data
library(lubridate) # Used to manipulate dates
library(dplyr) # Used to manipulate data
library(RecordLinkage) # used to clean up duplicates in the data
library(phonics) # used to extract phonetic version of names

##### Set date origin #####
origin <- "1970-01-01"

##### Define global useful functions #####

##### Connect to SQL servers #####
db.claims51 <- odbcConnect("PHClaims51")

##### Bring in Medicaid eligibility data for linking addresses by time period to clean address table processing #####
#Note to bring in test subset of Medicaid data, insert "top 50000" between SELECT and z.FIRST COLUMN
ptm01 <- proc.time() # Times how long this query takes - 172 sec
elig_gender <- sqlQuery(
  db.claims51,
  " select distinct y.CLNDR_YEAR_MNTH as calmo, y.MEDICAID_RECIPIENT_ID as id, y.GENDER as gender
    FROM (
    select z.CLNDR_YEAR_MNTH, z.MEDICAID_RECIPIENT_ID, z.GENDER
      FROM [PHClaims].[dbo].[NewEligibility] as z
    ) as y",
  stringsAsFactors = FALSE
  )
proc.time() - ptm01

##### Convert calendar month to calendar start and end dates for interval overlap comparison #####
elig_gender <- elig_gender %>%
  mutate(
    calstart = ymd(paste(as.character(calmo), "01", sep = "")),
    calend = ymd(paste(as.character(calmo), days_in_month(ymd(paste(as.character(calmo), "01", sep = ""))), sep = ""))
  )

##### Set gender to UPPERCASE #####
elig_gender <- elig_gender %>%
  mutate_at(
    vars(gender),
    toupper
  )

#### Create alone or in combination gender variables ####
elig_gender <- elig_gender %>%
  mutate(
    female = ifelse(str_detect(gender, "FEMALE"), 1, 0),
    male = ifelse(str_detect(gender, "^MALE$"), 1, 0)
  )


##### For each gender variable, count number of rows where variable = 1. ##### 
##### Divide this number by total number of rows (eg months) where gender is non-missing. ##### 
##### Create _t variables for each gender variable to hold this percentage. ##### 


#Create a variable to flag if all race vars are NA where Not Hispanic is considered NA as well
elig_gender <- elig_gender %>%
  mutate(
    genderna = is.na(gender)
  )

#Create gender person time vars
elig_gender <- elig_gender %>%
  group_by(id) %>%
  mutate(
    female_t = round((length(female[female == 1 & !is.na(female)]) / length(genderna[genderna == FALSE]) * 100), 1),
    male_t = round((length(male[male == 1 & !is.na(male)]) / length(genderna[genderna == FALSE]) * 100), 1)
  ) %>%
  ungroup()

#Replace NA person time variables with 0
elig_gender <- elig_gender %>%
  mutate_at(
    vars(female_t, male_t),
    recode, .missing = 0
  )

#### Copy all non-missing gender variable values to all rows within each ID. ####
elig_gender <- elig_gender %>%
  group_by(id) %>%
  mutate_at(
    vars(female, male),
    funs(max(., na.rm = TRUE))
  ) %>%
  ungroup()

#Replace infinity values with NA (these were generated by max function applied to NA rows)
elig_gender <- elig_gender %>%
  mutate_at(
    vars(female, male),
    function(x) replace(x, is.infinite(x),NA)
  )

##### Collapse to one row per ID given we have alone or in combo EVER gender variables #####
elig_gender_final <- distinct(elig_gender, id, female, male, female_t, male_t)

#Test to make sure no IDs are duplicated
test <- elig_gender_final %>%
  group_by(id) %>%
  count(id)

#Test to make sure all IDs in original data table are included in final
count(distinct(elig_gender_final, id))
count(distinct(elig_gender, id))

##### Save dob.mcaid_elig_gender to SQL server 51 #####
#This took 53 mins for 851,573 obs with 5 variables
#sqlDrop(db.claims51, "dbo.mcaid_elig_gender") # Commented out because not always necessary
ptm03 <- proc.time() # Times how long this query take
sqlSave(
  db.claims51,
  elig_gender_final,
  tablename = "dbo.mcaid_elig_gender",
  rownames = FALSE,
  fast = TRUE,
  varTypes = c(
    id = "Varchar(255)"
  )
)
proc.time() - ptm03














