--Eli Kern
--Assessment, Policy Development & Evaluation, Public Health - Seattle & King County
--6/27/18
--Code to return a claim summary for a member cohort generated by the Medicaid eligibility cohort function

--#######################
--STEP 1: Join eligibility temp table (generated by a separate stored procedure) to claim summary using IDs from former
--#######################

declare @from_date date, @to_date date

set @from_date = '2016-04-01'
set @to_date = '2017-03-31'

select query_from_date = @from_date, query_to_date = @to_date, elig.*, claim.mental_dx1_cnt, claim.mental_dxany_cnt, claim.maternal_dx1_cnt, claim.maternal_broad_dx1_cnt,
	claim.newborn_dx1_cnt, claim.inpatient_cnt, claim.ed_cnt, claim.ed_nohosp_cnt, claim.ed_avoid_ca_cnt, claim.ed_avoid_ca_nohosp_cnt,
	claim.mental_dx_rda_any_cnt, claim.sud_dx_rda_any_cnt, case when claim.ed_cnt is null then 1 else 0 end as 'no_claims'

from (
	select * from ##mcaidcohort
) as elig

left join (
	select b.id,
			sum(b.mental_dx1) as 'mental_dx1_cnt', sum(b.mental_dxany) as 'mental_dxany_cnt',
			sum(b.maternal_dx1) as 'maternal_dx1_cnt', sum(b.maternal_broad_dx1) as 'maternal_broad_dx1_cnt',
			sum(b.newborn_dx1) as 'newborn_dx1_cnt', sum(b.inpatient) as 'inpatient_cnt', sum(b.ipt_medsurg) as 'ipt_medsurg_cnt',
			sum(b.ipt_bh) as 'ipt_bh_cnt', sum( b.ed) as 'ed_cnt', sum(b.ed_nohosp) as 'ed_nohosp_cnt', sum(b.ed_avoid_ca) as 'ed_avoid_ca_cnt', 
			sum(b.ed_avoid_ca_nohosp) as 'ed_avoid_ca_nohosp_cnt', sum(b.mental_dx_rda_any) as 'mental_dx_rda_any_cnt', sum(b.sud_dx_rda_any) as 'sud_dx_rda_any_cnt'

	from (
		select a.id,
			max(a.mental_dx1) as 'mental_dx1', max(a.mental_dxany) as 'mental_dxany',
			max(a.maternal_dx1) as 'maternal_dx1', max(a.maternal_broad_dx1) as 'maternal_broad_dx1',
			max(a.newborn_dx1) as 'newborn_dx1', max(a.inpatient) as 'inpatient', max(a.ipt_medsurg) as 'ipt_medsurg',
			max(a.ipt_bh) as 'ipt_bh', max( a.ed) as 'ed', max(a.ed_nohosp) as 'ed_nohosp', max(a.ed_avoid_ca) as 'ed_avoid_ca', 
			max(a.ed_avoid_ca_nohosp) as 'ed_avoid_ca_nohosp', max(a.mental_dx_rda_any) as 'mental_dx_rda_any', max(a.sud_dx_rda_any) as 'sud_dx_rda_any'

		from (
			select id from ##mcaidcohort
		) as id

		left join (
			select * from PHClaims.dbo.mcaid_claim_summary
			where from_date <= @to_date and to_date >= @from_date
		) as a
		on id.id = a.id
		group by a.id, a.from_date
	) as b
	group by b.id
) as claim
on elig.id = claim.id