table_file_path: APCD_Tables_20241217.xlsx
ftp_url: https://mft.kingcounty.gov/api/v2.0/files/APDEDE-WA-APCD/WA-APCD/
ftp_keyring: apcd_sftp
db_name: hhs_analytics_workspace
server_path: hhsaw_dev
odbc_name: hhsaw_dev
base_dir: C:/temp/apcd
ref_dir: ref_schema
stage_dir: stage_schema
final_dir: final_schema
field_term: \t
row_term: \n
schema_name: jwhitehurst
ref_pre: ref
stage_pre: stage
final_pre: final
etl_table: z_apcd_etl_log
archive_suffix: _archive
index_type: ccs
index_prefix: idx_ccs_
