table_file_path: APCD_Tables_20240801.xlsx
ftp_url: https://mft.kingcounty.gov/api/v2.0/files/APDEDE-WA-APCD/WA-APCD/
ftp_keyring: apcd_sftp
db_name: APCD
server_path: DPHXPHA51AE0ECO
odbc_name: apcd
base_dir: C:/temp/apcd
ref_dir: ref_schema
stage_dir: stage_schema
final_dir: final_schema
field_term: \t
row_term: \n
ref_schema: ref
stage_schema: stage
final_schema: final
etl_table: apcd_etl_log
archive_suffix: _archive
index_type: ccs
index_prefix: idx_ccs_
