table_file_path: APCD_tables_20220609.xlsx
ftp_url: https://mft.kingcounty.gov/api/v2.0/files/APDEDE-WA-APCD/WA-APCD/
ftp_keyring: apcd_sftp
db_name: PHClaims
server_path: KCITSQLPRPENT40
odbc_name: PHClaims
base_dir: //dphcifs/apde-cdip/apcd/apcd_data_import/
ref_dir: ref_schema
stage_dir: stage_schema
final_dir: final_schema
field_term: \t
row_term: \n
ref_schema: ref
stage_schema: stage
final_schema: final
etl_table: apcd_etl_log
archive_suffix: _archive
index_type: ccs
index_prefix: idx_ccs_
